name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Build the project
        run: npm run build
        working-directory: ./

      - name: Debug paths
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "dist folder:"
          ls -la dist || echo "dist does not exist"
        working-directory: ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist